using System.Text;
using System.Web;

namespace IntuneMonitor.Reporting;

/// <summary>
/// Shared helpers for HTML report generation. Eliminates duplicated Encode, Truncate,
/// AppendCard, WriteAsync, and HTML skeleton code across report generators.
/// </summary>
internal static class HtmlReportHelpers
{
    /// <summary>HTML-encodes a string, replacing <c>null</c> with "(null)".</summary>
    public static string Encode(string? value) =>
        HttpUtility.HtmlEncode(value ?? "(null)");

    /// <summary>Truncates a string to a maximum length, appending "…" if truncated.</summary>
    public static string Truncate(string? value, int maxLength) =>
        value == null ? "(null)" :
        value.Length <= maxLength ? value :
        value[..maxLength] + "…";

    /// <summary>Appends a summary card div to the HTML builder.</summary>
    public static void AppendCard(StringBuilder sb, string label, string value, string cssClass)
    {
        sb.AppendLine($"<div class=\"card {cssClass}\">");
        sb.AppendLine($"<div class=\"card-value\">{Encode(value)}</div>");
        sb.AppendLine($"<div class=\"card-label\">{Encode(label)}</div>");
        sb.AppendLine("</div>");
    }

    /// <summary>Appends a "no data" placeholder section.</summary>
    public static void AppendNoDataSection(StringBuilder sb, string message)
    {
        sb.AppendLine($"<section class=\"no-changes\"><p>{Encode(message)}</p></section>");
    }

    /// <summary>
    /// Appends a breakdown table with name/count pairs, sorted by count descending.
    /// Used by audit and similar reports for activity type, component, and actor breakdowns.
    /// </summary>
    public static void AppendBreakdownTable(StringBuilder sb, string title, Dictionary<string, int> data)
    {
        sb.AppendLine("<section class=\"content-type\">");
        sb.AppendLine($"<h2>{Encode(title)} <span class=\"badge\">{data.Count}</span></h2>");
        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr><th>Name</th><th>Count</th></tr></thead>");
        sb.AppendLine("<tbody>");

        foreach (var (name, count) in data.OrderByDescending(kv => kv.Value))
        {
            sb.AppendLine("<tr>");
            sb.AppendLine($"<td class=\"policy-name\">{Encode(name)}</td>");
            sb.AppendLine($"<td>{count}</td>");
            sb.AppendLine("</tr>");
        }

        sb.AppendLine("</tbody></table>");
        sb.AppendLine("</section>");
    }

    /// <summary>
    /// Appends the standard HTML document opening: DOCTYPE, head, meta, styles, body,
    /// header with title/subtitle/theme toggle.
    /// </summary>
    public static void AppendDocumentHead(
        StringBuilder sb,
        string pageTitle,
        string headerTitle,
        string subtitle,
        string? subtitle2 = null,
        string? extraStyles = null)
    {
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"<title>{Encode(pageTitle)}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(HtmlTheme.GetStyles());
        if (!string.IsNullOrEmpty(extraStyles))
            sb.AppendLine(extraStyles);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body class=\"dark\">");

        sb.AppendLine("<header>");
        sb.AppendLine("<div class=\"header-row\">");
        sb.AppendLine("<div>");
        sb.AppendLine($"<h1>{Encode(headerTitle)}</h1>");
        sb.AppendLine($"<p class=\"meta\">{subtitle}</p>");
        if (!string.IsNullOrEmpty(subtitle2))
            sb.AppendLine($"<p class=\"meta\">{subtitle2}</p>");
        sb.AppendLine("</div>");
        sb.AppendLine("<button id=\"theme-toggle\" onclick=\"toggleTheme()\" title=\"Toggle light/dark mode\">&#9788;</button>");
        sb.AppendLine("</div>");
        sb.AppendLine("</header>");
    }

    /// <summary>
    /// Appends the standard HTML document closing: footer, theme-toggle script, body/html.
    /// </summary>
    public static void AppendDocumentFoot(StringBuilder sb)
    {
        sb.AppendLine("<footer>Generated by IntuneMonitor</footer>");
        sb.AppendLine("<script>");
        sb.AppendLine(HtmlTheme.GetScript());
        sb.AppendLine("</script>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
    }

    /// <summary>
    /// Generates HTML from a builder delegate and writes it to a file.
    /// Consolidates the Generate → Write pattern used by all report generators.
    /// </summary>
    public static async Task GenerateAndWriteAsync(
        Func<string> generateHtml,
        string outputPath,
        CancellationToken cancellationToken = default)
    {
        var html = generateHtml();
        await WriteHtmlAsync(html, outputPath, cancellationToken);
    }

    /// <summary>
    /// Writes the given HTML content to a file, creating intermediate directories as needed.
    /// </summary>
    public static async Task WriteHtmlAsync(string html, string outputPath, CancellationToken cancellationToken = default)
    {
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(dir))
            Directory.CreateDirectory(dir);

        await File.WriteAllTextAsync(outputPath, html, Encoding.UTF8, cancellationToken);
    }
}
